spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/camput?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
#    username: gigi
#    password: camp1234
#    driver-class-name: com.mysql.cj.jdbc.Driver
  datasource:
    url: jdbc:h2:tcp://localhost/~/practice3
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # show_sql: true
        format_sql: true

social:
  client:
    kakao:
      rest-api-key: ba50165094c8a6717bca69e014ef797d
      secret-key: nN7IyomDVGAkJm4z5nln24jQLiJzBG7Q
      grant_type: authorization_code
      redirect-uri: http://localhost:8081/camput/login/api-login
      admin-key: 09eca5bad30d56c0c80352f2eceecfa4
      logout-redirect-uri: http://localhost:8081/camput/logout

logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace

server:
  port: 8081
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

